GITHUB_TOKEN = "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"
REPLICATE_API_TOKEN = "r8_VrDGxofCfTbldOlIKMr3jeEtutugmVw3qJIIH"
REPLICATE_MODEL_ENDPOINTSTABILITY = "stability-ai/sdxl:2b017d9b67edd2ee1401238df49d75da53c523f36e363881e057f5dc3ed3c5b2"